### ISSUE TITLE
PLUS ruleset update (vaccinations)

### ISSUE THREAD

**Issue by AnKosteck** [digital-blueprint/dcc-at-rule-sets#3]
Please update the PLUS ruleset for conformity with the new vaccination rules.

- First full vaccination (2 vaccs  or recovery + 1 vacc) should be valid for 180 days
- booster vaccination (3 vaccs oder Genesung + 2 vaccs) for the full 270 days

As far as I can tell the business rulesets need to be updated?

**Comment by lazka** [comment]
thanks.

when should these rules be in effect (now?)

**Comment by AnKosteck** [comment]
Please update the ruleset until the first of March. They have to be active in the next term.

Just to be sure: Is the "new" rule regarding Janssen vaccinations (they need a second vacc now) which has come into effect in early January already implemented?

**Comment by lazka** [comment]
> Please update the ruleset until the first of March. They have to be active in the next term.

ok, thanks.

> Just to be sure: Is the "new" rule regarding Janssen vaccinations (they need a second vacc now) which has come into effect in early January already implemented?

I'll have a look. I'll sync things with the official rule set which seems to have various new rules for J&J: https://github.com/digital-blueprint/dgc-trust-mirror/blob/main/prod.json/rules-at.md

**Comment by lazka** [comment]
Sorry for the delay. It's all in sync with the official rules now.

**Comment by AnKosteck** [comment]
Thanks a lot!
